version: '3'
services:
  bond-service:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.ci
    volumes:
    - ./db/:/www/bond-service/db/
    ports:
      - "8000:8000"
    # entrypoint: >
    #  /bin/bash -c "cat /etc/debian_version"

